server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # API 요청을 백엔드로 프록시하는 설정
	# http://localhost:8383/api/getVehicle 이 들어오면
	# proxy_pass로 주소를 변경해서 연결해줌.
    location /api/ { # /api 로 시작하는 요청을 보낼 경우, 해당 요청을 Nginx가 처리
        proxy_pass http://coding404-api-gateway.default.svc.cluster.local:8383; # 백엔드 서버 주소
        proxy_set_header Host $host; # 클라이언트가 보낸 Host 헤더를 유지
        proxy_set_header X-Real-IP $remote_addr; # 클라이언트의 실제 IP 전달
    }

    error_page 404 /index.html;
}
