spring.application.name=PositionSimulator


server.port=8181

# rabbitMQ settings
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

position.queue=positionQueue