spring.application.name=PositionSimulator


server.port=8181

# rabbitMQ settings
# 쿠버네티스서비스명.default.svc.cluster.local
spring.rabbitmq.host=coding404-queue
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

position.queue=positionQueue